### ISSUE TITLE
Language robustness of F0 network

### ISSUE THREAD

**Issue by hc71-yoon** [yl4579/HiFTNet#6]
The quality of demo samples seems to be quite good, even in noisy environments or for unseen languages. Did you use the same f0 network (pretrained on LibriTTS) for these out-of-domain experiments? I'm also wondering whether it's okay to use the F0 network as is for unseen languages. If you have any experimental insights, I'd appreciate learning about them.

**Comment by yl4579** [comment]
Yes, I used the same model (download link in README) and F0 models (uploaded to the repo). F0 is independent of the language, so it should work quite well, and it even works for languages.
